group: blanco
name: train-prop-pack-sd
version: "2.0"
subfolder: 100-props-textures
assets:
  - assetId: blanco-train-prop-pack-sd
info:
  summary: Train Prop Pack
  author: blanco
  website: https://www.toutsimcities.com/downloads/view/1335

---
assetId: blanco-train-prop-pack-sd
version: "2.0"
lastModified: "2008-12-01T12:00:00Z"
url: https://www.toutsimcities.com/downloads/start/1335
