group: blanco
name: train-prop-pack
version: "2.0-1"
subfolder: 100-props-textures
dependencies: [ "blanco:transport-prop-pack" ]
info:
  summary: "Superseded by `pkg=blanco:transport-prop-pack`"
  author: blanco
  website: "https://www.toutsimcities.com/downloads/view/1573"

---
# This one uses different TGIs
group: blanco
name: train-prop-pack-sd
version: "1.0-1"
subfolder: 100-props-textures
dependencies: [ "blanco:transport-prop-pack" ]
info:
  summary: "Superseded by `pkg=blanco:transport-prop-pack`"
  author: blanco
  website: "https://www.toutsimcities.com/downloads/view/1335"
