group: blanco
name: train-prop-pack
version: "2.0"
subfolder: 100-props-textures
dependencies: [ "blanco05:transport-prop-pack" ]
assets:
  - assetId: blanco-train-prop-pack
info:
  summary: "Superseded by `pkg=blanco05:transport-prop-pack`"
  author: blanco
  website: "https://www.toutsimcities.com/downloads/view/1573"

---
# This one uses different TGIs
group: blanco
name: train-prop-pack-sd
version: "1.0"
subfolder: 100-props-textures
dependencies: [ "blanco05:transport-prop-pack" ]
assets:
  - assetId: blanco-train-prop-pack-sd
info:
  summary: "Superseded by `pkg=blanco05:transport-prop-pack`"
  author: blanco
  website: "https://www.toutsimcities.com/downloads/view/1335"

