group: blanco
name: train-prop-pack
version: "2.0"
subfolder: 100-props-textures
dependencies: [ "blanco:transport-prop-pack" ]
assets:
  - assetId: blanco-train-prop-pack
info:
  summary: "Superseded by `pkg=blanco:transport-prop-pack`"
  author: blanco

---
assetId: blanco-train-prop-pack
version: "2.0"
lastModified: "2009-07-30T12:00:00Z"


---
# This one uses different TGIs
group: blanco
name: train-prop-pack-sd
version: "1.0"
subfolder: 100-props-textures
dependencies: [ "blanco:transport-prop-pack" ]
assets:
  - assetId: blanco-train-prop-pack-sd
info:
  summary: "Superseded by `pkg=blanco:transport-prop-pack`"
  author: blanco

---
assetId: blanco-train-prop-pack-sd
version: "1.0"
lastModified: "2008-12-01T12:00:00Z"

