group: sm2
name: train-depot-north
version: "2.0.0"
subfolder: 700-transit
info:
  summary: Train Depot North
  description: |-
    This smaller and more compact train depot was made in order to fit better in tight spaces.

    Connect to a single track rail spur for best visual effect.

    You will find it under the heavy rail menu.

     - Lot size: 6x5
     - Power req: 25
     - Water req: 10
     - Plop cost: 9000
     - Bulldoze cost: 400
     - Provides 85 jobs
  author: Simmer2
  website: https://community.simtropolis.com/files/file/34604-sm2-train-depot-north/
  images:
    - https://www.simtropolis.com/objects/screens/monthly_2021_07/tdn1.jpg.95fc16e366e7808a6a4aa272b7043387.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2021_07/tdn2.jpg.06ba38c2e4e2d6e8816bfd4ae96efb7b.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2021_07/tdn3.jpg.b6ed7feeb9d12ca985213da40e6fd810.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2021_07/tdn4.jpg.79289bca3e3f600dabe248515b3309d7.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2021_07/tdn5.jpg.83e1956ede1bb69aeb5688b11374b232.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2021_07/tdn6.jpg.7df1bbf1f83c1364244cf7a5f43dc46b.jpg
dependencies:
  - sm2:essentials
  - sm2:mega-prop-pack-vol1
  - sm2:mega-prop-pack-vol2
  - sm2:mega-prop-pack-vol3
  - sm2:mega-prop-pack-vol4
  - sm2:mega-prop-pack-vol5
  - sm2:mega-prop-pack-vol6
  - bsc:vip-girafe-carpack-vol01-vol02
assets:
  - assetId: sm2-train-depot-north

---
assetId: sm2-train-depot-north
version: "2.0.0"
lastModified: "2022-02-25T17:56:38Z"
url: https://community.simtropolis.com/files/file/34604-sm2-train-depot-north/?do=download
