group: sm2
name: train-depot-east
version: "1.0.0"
subfolder: 400-industrial
info:
  summary: Train Depot East
  description: |-
    A fictional train depot on a large lot for those rail heads out there.

    This lot is not a freight yard but it will connect with your RRW DTR network and the dirt road SAM for that seamless look. Make sure you flatten the terrain before placing.

    It also  - Provides 150 jobs

     - Lot size: 16X5
     - Plop cost: 25000
     - Bulldoze cost: 1500
     - Power req: 10
     - Water req: 5
     - Provides 150 jobs
  author: Simmer2
  website: https://community.simtropolis.com/files/file/33155-sm2-train-depot-east/
  images:
    - https://www.simtropolis.com/objects/screens/monthly_2019_09/td.jpg.d7e82087f71acb18db432b37df4a1889.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2019_09/td2.jpg.e8d70cee2bcdfc5e9783aa26f3c5432e.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2019_09/td3.jpg.9a55d20c3d7cdbb58b326482218950c5.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2019_09/td4.jpg.b73f9ad8462880e4ba00069fe8dfe0ea.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2019_09/td5.jpg.7eb193e8751559e7e098fe8aa13409d9.jpg
dependencies:
  - sm2:essentials
  - sm2:mega-prop-pack-vol1
  - sm2:mega-prop-pack-vol2
  - sm2:mega-prop-pack-vol3
  - sm2:mega-prop-pack-vol4
  - bsc:vip-girafe-carpack-vol01-vol02
  - girafe:bushes
  - girafe:beeches
  - girafe:common-spruces
  - girafe:poplars
  - girafe:daisy
  - angry-mozart:na-locomotive-props
assets:
  - assetId: sm2-train-depot-east

---
assetId: sm2-train-depot-east
version: "1.0.0"
lastModified: "2019-12-02T05:24:15Z"
url: https://community.simtropolis.com/files/file/33155-sm2-train-depot-east/?do=download
