group: "gizmo"
name: "train-props-collection"
version: "1.0"
subfolder: "100-props-textures"
assets:
- assetId: "gizmo-train-props-collection"
info:
  summary: "Gizmo - Train Props Collection"
  description: |-
    This is a compilation of 16 train/rail car prop sets created by several members of the SC4 community, including Gizmo, and originally were compiled together by Gizmo.
  author: "Gizmo"
  websites:
    - "https://www.sc4evermore.com/index.php/downloads/download/22-dependencies/66-gizmo-train-props-collection"

---
assetId: "gizmo-train-props-collection"
version: "1.0"
lastModified: "2023-07-27T11:52:36-07:00"
url: "https://www.sc4evermore.com/index.php/downloads?task=download.send&id=66:gizmo-train-props-collection"