name: auto-update

on:
  schedule:
    - cron: '15 16 * * 0,3,5,6'  # 4:15 pm UTC on Sundays, Wednesdays, Fridays, Saturdays
  workflow_dispatch:

jobs:
  auto-update:
    uses: memo33/sc4pac-actions/.github/workflows/sc4pac-channel-updates.yaml@main
    with:
      path: src/yaml
      deploy-repository: memo33/sc4pac
    secrets:
      stex-api-key: ${{ secrets.STEX_API_KEY }}
      pat: ${{ secrets.SC4PAC_CHECK_UPDATES_TOKEN }}
    permissions:
      pull-requests: write
